export const KINGDOM_SEED_VERSION = "2.36.21";
export const KINGDOM_SEED_BUILD_LABEL = "REFERENCE VARIANT MATRIX";
export const KINGDOM_SEED_BUILD_NAME = `v${KINGDOM_SEED_VERSION} ${KINGDOM_SEED_BUILD_LABEL}`;
