export const KINGDOM_SEED_VERSION = "2.36.20";
export const KINGDOM_SEED_BUILD_LABEL = "REFERENCE EVOLUTION PIPELINE";
export const KINGDOM_SEED_BUILD_NAME = `v${KINGDOM_SEED_VERSION} ${KINGDOM_SEED_BUILD_LABEL}`;
