export const KINGDOM_SEED_VERSION = "2.36.22";
export const KINGDOM_SEED_BUILD_LABEL = "REFERENCE PROGRESSION FUSION";
export const KINGDOM_SEED_BUILD_NAME = `v${KINGDOM_SEED_VERSION} ${KINGDOM_SEED_BUILD_LABEL}`;
